name: cf
channels:
  - conda-forge
  - defaults
  - bioconda
  - anaconda
dependencies:
  - python
  - scikit-learn
  - pandas
  - seaborn
  - jupyter
  - pytest
  - black
  - isort
  - pylint
  #- pip:
  #- qmplot == 0.2.0
